# Generated by Django 4.1.2 on 2022-12-15 15:18

from django.db import migrations, models
import django.db.models.deletion
import thoughtsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to=thoughtsapp.models.getfilename)),
                ('type', models.CharField(max_length=30)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughtsapp.catagory')),
            ],
        ),
    ]
