# Generated by Django 4.1.2 on 2022-12-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtsapp', '0002_post_created_at_createpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='title',
            new_name='new_cat',
        ),
    ]
