# Generated by Django 4.1.2 on 2022-12-20 02:53

from django.db import migrations, models
import thoughtsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtsapp', '0004_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='image',
            field=models.FileField(upload_to=thoughtsapp.models.getfilename),
        ),
    ]
